sudo: false
language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.0

addons:
  postgresql: '9.6'
services:
  - postgresql
  - redis-server

cache:
  directories:
    - _build
    - deps

branches:
  only:
    - master
