sudo: false
language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0

addons:
  postgresql: '9.6'
services:
  - postgresql

cache:
  directories:
    - _build
    - deps

branches:
  only:
    - master